//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.05 at 07:54:39 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ru.rr27.soapserviceexample/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.rr27.soapserviceexample.soap;
